Repository berkethetechnerd/ALPS-DeviceTracking, pull requests merged in 2020-12, with the labels that each got.

#4 Login Page added
  DeviceTracking/app/build.gradle
  DeviceTracking/app/src/main/AndroidManifest.xml
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/BaseActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/LoginActivity.kt
  DeviceTracking/app/src/main/res/drawable-hdpi/ic_logo.png
  DeviceTracking/app/src/main/res/drawable-mdpi/ic_logo.png
  DeviceTracking/app/src/main/res/drawable-xhdpi/ic_logo.png
  DeviceTracking/app/src/main/res/drawable-xxhdpi/ic_logo.png
  DeviceTracking/app/src/main/res/layout/activity_login.xml
  DeviceTracking/app/src/main/res/values/strings.xml
Labels: new feature

#5 Sensor selection
  DeviceTracking/app/build.gradle
  DeviceTracking/app/src/main/AndroidManifest.xml
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/LoginActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/SensorSelectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/views/SensorView.kt
  DeviceTracking/app/src/main/res/drawable/ic_bluetooth_sensor.xml
  DeviceTracking/app/src/main/res/drawable/ic_screen_usage_sensor.xml
  DeviceTracking/app/src/main/res/drawable/ic_wifi_sensor.xml
  DeviceTracking/app/src/main/res/layout/activity_dummy.xml
  DeviceTracking/app/src/main/res/layout/activity_sensor_selection.xml
  DeviceTracking/app/src/main/res/layout/view_sensor.xml
  DeviceTracking/app/src/main/res/values/strings.xml
Labels: new feature

#16 Report screen
  DeviceTracking/.idea/jarRepositories.xml
  DeviceTracking/app/build.gradle
  DeviceTracking/app/src/main/AndroidManifest.xml
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/DataCollectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ReportScreenActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/SensorSelectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/DummyDataGenerator.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/SectionsPagerAdapter.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/fragments/BluetoothUsageFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/fragments/ScreenUsageFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/fragments/WifiUsageFragment.kt
  DeviceTracking/app/src/main/res/drawable-hdpi/ic_data.png
  DeviceTracking/app/src/main/res/drawable-mdpi/ic_data.png
  DeviceTracking/app/src/main/res/drawable-xhdpi/ic_data.png
  DeviceTracking/app/src/main/res/drawable-xxhdpi/ic_data.png
  DeviceTracking/app/src/main/res/drawable-xxxhdpi/ic_data.png
  DeviceTracking/app/src/main/res/layout/activity_report_screen.xml
  DeviceTracking/app/src/main/res/layout/fragment_bluetooth_usage.xml
  DeviceTracking/app/src/main/res/layout/fragment_screen_usage.xml
  DeviceTracking/app/src/main/res/layout/fragment_wifi_usage.xml
  DeviceTracking/app/src/main/res/menu/menu_report.xml
  DeviceTracking/app/src/main/res/values-w820dp/dimens.xml
  DeviceTracking/app/src/main/res/values/dimens.xml
  DeviceTracking/app/src/main/res/values/strings.xml
  DeviceTracking/app/src/main/res/values/themes.xml
  DeviceTracking/build.gradle
  DeviceTracking/gradle/wrapper/gradle-wrapper.properties
Labels: new feature

#18 Bugs and refactoring
  DeviceTracking/app/build.gradle
  DeviceTracking/app/src/main/AndroidManifest.xml
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/BaseActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ConsentActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/DataCollectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/LoginActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ReportScreenActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/SensorSelectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/CalendarManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/Constants.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/DummyDataGenerator.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/SharedPreferencesManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/reporting/ColumnReportFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/reporting/SectionsPagerAdapter.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/SectionsPagerAdapter.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/fragments/BluetoothUsageFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/fragments/ScreenUsageFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ui/reports/fragments/WifiUsageFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/views/SensorView.kt
  DeviceTracking/app/src/main/res/drawable/ic_launcher_background.xml
  DeviceTracking/app/src/main/res/layout/activity_consent.xml
  DeviceTracking/app/src/main/res/layout/activity_data_collection.xml
  DeviceTracking/app/src/main/res/layout/activity_dummy.xml
  DeviceTracking/app/src/main/res/layout/activity_login.xml
  DeviceTracking/app/src/main/res/layout/activity_report_screen.xml
  DeviceTracking/app/src/main/res/layout/activity_sensor_selection.xml
  DeviceTracking/app/src/main/res/layout/fragment_bluetooth_usage.xml
  DeviceTracking/app/src/main/res/layout/fragment_column_report.xml
  DeviceTracking/app/src/main/res/layout/fragment_screen_usage.xml
  DeviceTracking/app/src/main/res/layout/fragment_wifi_usage.xml
  DeviceTracking/app/src/main/res/layout/view_sensor.xml
  DeviceTracking/app/src/main/res/menu/menu_report.xml
  DeviceTracking/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  DeviceTracking/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  DeviceTracking/app/src/main/res/mipmap-hdpi/ic_launcher.png
  DeviceTracking/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  DeviceTracking/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  DeviceTracking/app/src/main/res/mipmap-mdpi/ic_launcher.png
  DeviceTracking/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  DeviceTracking/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  DeviceTracking/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  DeviceTracking/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  DeviceTracking/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  DeviceTracking/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  DeviceTracking/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  DeviceTracking/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  DeviceTracking/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  DeviceTracking/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  DeviceTracking/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  DeviceTracking/app/src/main/res/values/dimens.xml
  DeviceTracking/app/src/main/res/values/strings.xml
Labels: bug, improvement

#22 Permission management
  DeviceTracking/app/build.gradle
  DeviceTracking/app/src/main/AndroidManifest.xml
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ApplicationClass.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/BaseActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ConsentActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/DataCollectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/LoginActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/SensorSelectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/delegates/PermissionDelegate.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/enums/AccessPermission.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/ConstantsManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/PermissionManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/SettingsManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/UserMessageGenerator.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/views/SensorView.kt
  DeviceTracking/app/src/main/res/values-night/themes.xml
  DeviceTracking/app/src/main/res/values/strings.xml
  DeviceTracking/app/src/main/res/values/themes.xml
Labels: improvement, new feature

#30 Wifi & Bluetooth tracking
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/BaseActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ConsentActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/DataCollectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/LoginActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/SensorSelectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/delegates/ActivationDelegate.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/delegates/SensorStatusDelegate.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/enums/AccessSensor.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/Broadcaster.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/DataCollectionManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/PermissionManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/RealmManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/SettingsManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/UserMessageGenerator.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/views/SensorView.kt
  DeviceTracking/app/src/main/res/layout/view_sensor.xml
  DeviceTracking/app/src/main/res/values/strings.xml
Labels: improvement, new feature

#31 Device Tracking [Foreground] - Screen Usage
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/DataCollectionActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/delegates/SensorStatusDelegate.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/Broadcaster.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/Logger.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/SettingsManager.kt
Labels: improvement, new feature

#34 Reporting - Real Data
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ApplicationClass.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/LoginActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/enums/CalendarDays.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/Broadcaster.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/CalendarManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/ConstantsManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/DataCollectionManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/DummyDataGenerator.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/Logger.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/PermissionManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/RealmManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/SettingsManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/SharedPreferencesManager.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/helper/UserMessageGenerator.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/model/SensorData.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/reporting/ColumnReportFragment.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/reporting/SectionsPagerAdapter.kt
  DeviceTracking/app/src/main/res/layout/fragment_column_report.xml
Labels: improvement, new feature

#35 Reporting - Modifications upon Feedback
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/ReportScreenActivity.kt
  DeviceTracking/app/src/main/java/com/alpsproject/devicetracking/reporting/ColumnReportFragment.kt
  DeviceTracking/app/src/main/res/layout/fragment_column_report.xml
  DeviceTracking/app/src/main/res/values/strings.xml
Labels: improvement
